version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  mysql:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "dev"
    ports:
      - "3306:3306"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: dev
      DB_HOST: database
      DB_PORT: 3306
      SECRET_KEY: secretKey
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
