version: "3.9"

services:
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=not.too.shabby
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: [ "npm", "run", "test" ]
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: not.too.shabby
      DB_DATABASE: postgres
      DB_PORT: 5432
      PORT: 3000
      SECRET_KEY: secretKey
      LOG_FORMAT: dev
      LOG_DIR: "../logs"
      ORIGIN: "*"
      CREDENTIALS: true
      NODE_ENV: "testing"
    depends_on:
      - database

volumes:
  postgres_data:
